### ISSUE TITLE
Web3Auth modal display is behind previous modal with RainbowKit

### ISSUE THREAD

**Issue by taijusanagi** [Web3Auth/web3auth-wagmi-connector#8]
Hi, I'm trying to integrate Web3Auth with wagmi with RainbowKit.

I'm following the demo example implementation, but the Web3Modal is displayed behind the RainbowKit modal.

<img width="1324" alt="Screen Shot 2022-10-08 at 18 35 21" src="https://user-images.githubusercontent.com/38043569/194733481-eddc5e91-988d-4118-9c6a-67f21c9ab008.png">

I can see the Web3Modal after close the RainbowKit modal.
Is there any way to fix this issue?

**Comment by wesleyfsmith** [comment]
Yup, same issue here, haven't found a fix for it yet.

**Comment by intertwine** [comment]
This problem happens because the RainbowKit modal has a very high z-index and Web3Modal div container does not have a css position attribute.

I fixed this issue by:

1. Adding an entry to my project's global css stylesheet to position the web3auth modal container:

```css
.w3a-parent-container {
    position: absolute
}
```

and

2. Forking and using my own copy of [web3auth-wagmi-connector](https://github.com/Web3Auth/web3auth-wagmi-connector/blob/master/src/lib/connector.ts) (in this repo) to add a higher z-index value to the web3auth modal configuration:

In: https://github.com/Web3Auth/web3auth-wagmi-connector/blob/master/src/lib/connector.ts#L91

```diff
...
      this.loginModal = new LoginModal({
            theme: this.options.uiConfig?.theme,
            appLogo: this.options.uiConfig?.appLogo,
            adapterListener: this.web3AuthInstance,
            displayErrorsOnModal: this.options.displayErrorsOnModal,
+           modalZIndex: `${2147483646 + 2}` ,
        });
...
```

The specific z-index value is chosen because of a [recent change in the RainbowKit modal code](https://github.com/rainbow-me/rainbowkit/blob/01f61336fcc252ef4475987b1b65d5dabee690c8/packages/rainbowkit/CHANGELOG.md) where they had to update their z-index to work well with the Coinbase wallet modal.

**Comment by chaitanyapotti** [comment]
This is fixed now
